# SPDX-License-Identifier: Apache-2.0

QEMU_OPTEE_ID := qemu-optee
QEMU_OPTEE_ARCH := aarch64
QEMU_OPTEE_BUILD_DIR := $(BUILD)/platforms/$(QEMU_OPTEE_ID)

QEMU_OPTEE_CC := aarch64-linux-gnu-gcc
QEMU_OPTEE_CFLAGS :=

QEMU_OPTEE_SECURE_BACKEND := optee
QEMU_OPTEE_ENABLE_ONNXRUNTIME := 1

QEMU_OPTEE_ORT_INCLUDE := external/onnxruntime-aarch64/include
QEMU_OPTEE_ORT_LIB := external/onnxruntime-aarch64/lib
QEMU_OPTEE_ORT_RPATH := /usr/lib

QEMU_OPTEE_SUPERVISOR := $(QEMU_OPTEE_BUILD_DIR)/tear-supervisor
QEMU_OPTEE_DEMO_MODEL := $(QEMU_OPTEE_BUILD_DIR)/demo-model
QEMU_OPTEE_MNIST_MODEL := $(QEMU_OPTEE_BUILD_DIR)/mnist-model
QEMU_OPTEE_RUNTIME_MANAGER := $(QEMU_OPTEE_BUILD_DIR)/tear-runtime-manager
QEMU_OPTEE_TRUSTD := $(QEMU_OPTEE_BUILD_DIR)/tear-trustd
QEMU_OPTEE_TEARICTL := $(QEMU_OPTEE_BUILD_DIR)/tearictl
QEMU_OPTEE_OPTD := $(QEMU_OPTEE_BUILD_DIR)/tear-optd

QEMU_OPTEE_OPTEE_TA_BUILD := $(QEMU_OPTEE_BUILD_DIR)/optee/tear_ta
QEMU_OPTEE_OPTEE_CA := $(QEMU_OPTEE_BUILD_DIR)/optee/tear-optee-ca
QEMU_OPTEE_OPTEE_TRUSTD := $(QEMU_OPTEE_BUILD_DIR)/optee/tear-trustd-optee
